import {
  type ThaiAlphabet,
  VowelGroup,
  VowelGroupOrder,
  ThaiAlphabetType,
  SpokenLength,
} from '@/app/types.d'

const vowels: ThaiAlphabet[] = [
  // e, short vowels
  {
    alphabet: 'อิ',
    order: 42,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อิ',
    thaiExampleDescription: '',
    romanTransliteration: 'e',
    romanDescription: 'E',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.first,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เ-ะ',
    order: 43,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-ะ',
    thaiExampleDescription: '',
    romanTransliteration: 'e',
    romanDescription: 'E',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.second,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'แ-ะ',
    order: 44,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'แ-ะ',
    thaiExampleDescription: '',
    romanTransliteration: 'ea',
    romanDescription: 'Ea',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.third,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เอียะ',
    order: 45,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เอียะ',
    thaiExampleDescription: '',
    romanTransliteration: 'ea',
    romanDescription: 'Ea',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Short,
  },
  // i, long vowels
  {
    alphabet: 'อี',
    order: 46,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อี',
    thaiExampleDescription: '',
    romanTransliteration: 'i',
    romanDescription: 'I',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.first,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: 'เ-',
    order: 47,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-',
    thaiExampleDescription: '',
    romanTransliteration: 'i',
    romanDescription: 'I',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.second,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: 'แ-',
    order: 48,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'แ-',
    thaiExampleDescription: '',
    romanTransliteration: 'ee',
    romanDescription: 'Ee',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.third,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: 'เอีย',
    order: 49,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เอีย',
    thaiExampleDescription: '',
    romanTransliteration: 'eea',
    romanDescription: 'Eea',
    vowelGroup: VowelGroup.first,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Long,
  },
  // o, short vowels
  {
    alphabet: 'อุ',
    order: 50,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อุ',
    thaiExampleDescription: '',
    romanTransliteration: 'u',
    romanDescription: 'U',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.first,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'โ-ะ',
    order: 51,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'โ-ะ',
    thaiExampleDescription: '',
    romanTransliteration: 'u',
    romanDescription: 'U',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.second,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เ-าะ',
    order: 52,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-าะ',
    thaiExampleDescription: '',
    romanTransliteration: 'u',
    romanDescription: 'U',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.third,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'อัวะ',
    order: 53,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อัวะ',
    thaiExampleDescription: '',
    romanTransliteration: 'ua',
    romanDescription: 'Ua',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Short,
  },
  // u, long vowels
  {
    alphabet: 'อู',
    order: 54,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อู',
    thaiExampleDescription: '',
    romanTransliteration: 'oo',
    romanDescription: 'Oo',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.first,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: 'เ-อะ',
    order: 55,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-อะ',
    thaiExampleDescription: '',
    romanTransliteration: 'ou',
    romanDescription: 'Ou',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.second,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: '-อ',
    order: 56,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: '-อ',
    thaiExampleDescription: '',
    romanTransliteration: 'u',
    romanDescription: 'U',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.third,
    spokenLength: SpokenLength.Long,
  },
  {
    alphabet: 'อัว',
    order: 57,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อัว',
    thaiExampleDescription: '',
    romanTransliteration: 'oua',
    romanDescription: 'Oua',
    vowelGroup: VowelGroup.second,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Long,
  },
  // u, short vowels
  {
    alphabet: 'อึ',
    order: 58,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อึ',
    thaiExampleDescription: '',
    romanTransliteration: 'ue',
    romanDescription: 'Ue',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.first,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เ-อะ',
    order: 59,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-อะ',
    thaiExampleDescription: '',
    romanTransliteration: 'ue',
    romanDescription: 'Ue',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.second,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: '-ะ',
    order: 60,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: '-ะ',
    thaiExampleDescription: '',
    romanTransliteration: 'u',
    romanDescription: 'U',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.third,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เอือะ',
    order: 61,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'ออือะ',
    thaiExampleDescription: '',
    romanTransliteration: 'uea',
    romanDescription: 'Uea',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'อือ',
    order: 62,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'อือ',
    thaiExampleDescription: '',
    romanTransliteration: 'ue',
    romanDescription: 'Ue',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: 'เ-อ',
    order: 63,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เ-อ',
    thaiExampleDescription: '',
    romanTransliteration: 'ue',
    romanDescription: 'Ue',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Short,
  },
  {
    alphabet: '-า',
    order: 64,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: '-า',
    thaiExampleDescription: '',
    romanTransliteration: 'ah',
    romanDescription: 'Ah',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.fourth,
  },
  {
    alphabet: 'เอือ',
    order: 65,
    type: ThaiAlphabetType.Vowel,
    thaiExamplePrefix: 'เอือ',
    thaiExampleDescription: '',
    romanTransliteration: 'uea',
    romanDescription: 'Uea',
    vowelGroup: VowelGroup.third,
    vowelGroupOrder: VowelGroupOrder.fourth,
    spokenLength: SpokenLength.Long,
  },
]

export default vowels