import { type ThaiAlphabet } from '../types'

const thaiAlphabet: ThaiAlphabet[] = [
  {
    alphabet: 'ก',
    thaiExamplePrefix: 'กอ',
    thaiExampleDescription: 'ไก่',
    romanTransliterationPrefix: 'gaw',
    romanTransliteration: 'gai',
    romanDescription: 'Chicken',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/gaw-gai.webp',
    order: 1
  },
  {
    alphabet: 'จ',
    thaiExamplePrefix: 'จอ',
    thaiExampleDescription: 'จาน',
    romanTransliterationPrefix: 'jauw',
    romanTransliteration: 'jaan',
    romanDescription: 'Plate',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/jauw-jaan.webp',
    order: 2
  },
  {
    alphabet: 'ด',
    thaiExamplePrefix: 'ดอ',
    thaiExampleDescription: 'เด็ก',
    romanTransliterationPrefix: 'daw',
    romanTransliteration: 'dek',
    romanDescription: 'Child',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/daw-dek.webp',
    order: 3
  },
  {
    alphabet: 'ฎ',
    thaiExamplePrefix: 'ฎอ',
    thaiExampleDescription: 'ชฎา',
    romanTransliterationPrefix: 'daw',
    romanTransliteration: 'chada',
    romanDescription: 'Headdress',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/daw-chada.webp',
    order: 4
  },
  {
    alphabet: 'ต',
    thaiExamplePrefix: 'ตอ',
    thaiExampleDescription: 'เต่า',
    romanTransliterationPrefix: 'daw',
    romanTransliteration: 'dtao',
    romanDescription: 'Turtle',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/daw-dtao.webp',
    order: 5
  },
  {
    alphabet: 'ฏ',
    thaiExamplePrefix: 'ฏอ',
    thaiExampleDescription: 'ปฏัก',
    romanTransliterationPrefix: 'daw',
    romanTransliteration: 'padak',
    romanDescription: 'Goad (Cattle prod)',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/daw-padak.webp',
    order: 6
  },
  {
    alphabet: 'บ',
    thaiExamplePrefix: 'บอ',
    thaiExampleDescription: 'ใบไม้',
    romanTransliterationPrefix: 'baw',
    romanTransliteration: 'bai mai',
    romanDescription: 'Leaf',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/baw-bai-mai.webp',
    order: 7
  },
  {
    alphabet: 'ป',
    thaiExamplePrefix: 'ปอ',
    thaiExampleDescription: 'ปลา',
    romanTransliterationPrefix: 'baw',
    romanTransliteration: 'bplaa',
    romanDescription: 'Fish',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/baw-bplaa.webp',
    order: 8
  },
  {
    alphabet: 'อ',
    thaiExamplePrefix: 'ออ',
    thaiExampleDescription: 'อ่าง',
    romanTransliterationPrefix: 'aw',
    romanTransliteration: 'ang',
    romanDescription: 'Basin',
    isConsonant: true,
    consonantGroup: 'middle',
    imageSrc: '/aw-ang.webp',
    order: 9
  },
  {
    alphabet: 'ข',
    thaiExamplePrefix: 'ขอ',
    thaiExampleDescription: 'ไข่',
    romanTransliterationPrefix: 'kaw',
    romanTransliteration: 'khai',
    romanDescription: 'Egg',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/kaw-khai.webp',
    order: 10
  },
  {
    alphabet: 'ฉ',
    thaiExamplePrefix: 'ฉอ',
    thaiExampleDescription: 'ฉิ่ง',
    romanTransliterationPrefix: 'chaw',
    romanTransliteration: 'ching',
    romanDescription: 'Cymbals',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/chaw-ching.webp',
    order: 11
  },
  {
    alphabet: 'ถ',
    thaiExamplePrefix: 'ถอ',
    thaiExampleDescription: 'ถุง',
    romanTransliterationPrefix: 'taw',
    romanTransliteration: 'tung',
    romanDescription: 'Bag',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/taw-tung.webp',
    order: 12
  },
  {
    alphabet: 'ฐ',
    thaiExamplePrefix: 'ฐอ',
    thaiExampleDescription: 'ฐาน',
    romanTransliterationPrefix: 'taw',
    romanTransliteration: 'taan',
    romanDescription: 'Pedestal',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/taw-taan.webp',
    order: 13
  },
  {
    alphabet: 'ผ',
    thaiExamplePrefix: 'ผอ',
    thaiExampleDescription: 'ผึ้ง',
    romanTransliterationPrefix: 'paw',
    romanTransliteration: 'phung',
    romanDescription: 'Bee',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/paw-phung.webp',
    order: 14
  },
  {
    alphabet: 'ฝ',
    thaiExamplePrefix: 'ฝอ',
    thaiExampleDescription: 'ฝา',
    romanTransliterationPrefix: 'faw',
    romanTransliteration: 'faa',
    romanDescription: 'Lid',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/faw-faa.webp',
    order: 15
  },
  {
    alphabet: 'ศ',
    thaiExamplePrefix: 'ศอ',
    thaiExampleDescription: 'ศาลา',
    romanTransliterationPrefix: 'saw',
    romanTransliteration: 'sala',
    romanDescription: 'Pavilion',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/saw-sala.webp',
    order: 16
  },
  {
    alphabet: 'ษ',
    thaiExamplePrefix: 'ษอ',
    thaiExampleDescription: 'ฤๅษี',
    romanTransliterationPrefix: 'saw',
    romanTransliteration: 'ruusii',
    romanDescription: 'Hermit',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/saw-ruusii.webp',
    order: 17
  },
  {
    alphabet: 'ส',
    thaiExamplePrefix: 'สอ',
    thaiExampleDescription: 'เสือ',
    romanTransliterationPrefix: 'saw',
    romanTransliteration: 'suaa',
    romanDescription: 'Tiger',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/saw-suaa.webp',
    order: 18
  },
  {
    alphabet: 'ห',
    thaiExamplePrefix: 'หอ',
    thaiExampleDescription: 'หีบ',
    romanTransliterationPrefix: 'haw',
    romanTransliteration: 'heap',
    romanDescription: 'Chest',
    isConsonant: true,
    consonantGroup: 'high',
    imageSrc: '/haw-heap.webp',
    order: 19
  },
  {
    alphabet: 'ค',
    thaiExamplePrefix: 'คอ',
    thaiExampleDescription: 'ควาย',
    romanTransliterationPrefix: 'khaw',
    romanTransliteration: 'khwai',
    romanDescription: 'Buffalo',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/khaw-khwai.webp',
    order: 20
  },
  {
    alphabet: 'ฆ',
    thaiExamplePrefix: 'ฆอ',
    thaiExampleDescription: 'ระฆัง',
    romanTransliterationPrefix: 'kaw',
    romanTransliteration: 'rakang',
    romanDescription: 'Bell',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/kaw-rakang.webp',
    order: 21
  },
  {
    alphabet: 'ช',
    thaiExamplePrefix: 'ชอ',
    thaiExampleDescription: 'ช้าง',
    romanTransliterationPrefix: 'chaw',
    romanTransliteration: 'chaang',
    romanDescription: 'Elephant',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/chaw-chaang.webp',
    order: 22
  },
  {
    alphabet: 'ฌ',
    thaiExamplePrefix: 'ฌอ',
    thaiExampleDescription: 'เฌอ',
    romanTransliterationPrefix: 'chaw',
    romanTransliteration: 'cheur',
    romanDescription: 'Tree',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/chaw-cheur.webp',
    order: 23
  },
  {
    alphabet: 'ท',
    thaiExamplePrefix: 'ทอ',
    thaiExampleDescription: 'ทหาร',
    romanTransliterationPrefix: 'taw',
    romanTransliteration: 'thahaan',
    romanDescription: 'Soldier',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/taw-thahaan.webp',
    order: 24
  },
  {
    alphabet: 'ธ',
    thaiExamplePrefix: 'ธอ',
    thaiExampleDescription: 'ธง',
    romanTransliterationPrefix: 'taw',
    romanTransliteration: 'thong',
    romanDescription: 'Flag',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/taw-thong.webp',
    order: 25
  },
  {
    alphabet: 'ฒ',
    thaiExamplePrefix: 'ฒอ',
    thaiExampleDescription: 'ผู้เฒ่า',
    romanTransliterationPrefix: 'taw',
    romanTransliteration: 'putow',
    romanDescription: 'Elder',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/taw-putow.webp',
    order: 26
  },
  {
    alphabet: 'พ',
    thaiExamplePrefix: 'พอ',
    thaiExampleDescription: 'พาน',
    romanTransliterationPrefix: 'phaw',
    romanTransliteration: 'phaan',
    romanDescription: 'Pedestal tray',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/phaw-phaan.webp',
    order: 27
  },
  {
    alphabet: 'ภ',
    thaiExamplePrefix: 'ภอ',
    thaiExampleDescription: 'สำเภา',
    romanTransliterationPrefix: 'phaw',
    romanTransliteration: 'samphao',
    romanDescription: 'Sailing ship',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/phaw-samphao.webp',
    order: 28
  },
  {
    alphabet: 'ฟ',
    thaiExamplePrefix: 'ฟอ',
    thaiExampleDescription: 'ฟัน',
    romanTransliterationPrefix: 'faw',
    romanTransliteration: 'fun',
    romanDescription: 'Tooth',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/faw-fun.webp',
    order: 29
  },
  {
    alphabet: 'ซ',
    thaiExamplePrefix: 'ซอ',
    thaiExampleDescription: 'โซ่',
    romanTransliterationPrefix: 'saw',
    romanTransliteration: 'soo',
    romanDescription: 'Chain',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/saw-soo.webp',
    order: 30
  },
  {
    alphabet: 'ฮ',
    thaiExamplePrefix: 'ฮอ',
    thaiExampleDescription: 'นกฮูก',
    romanTransliterationPrefix: 'hoo',
    romanTransliteration: 'nok hook',
    romanDescription: 'Owl',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/hoo-nok-hook.webp',
    order: 31
  },
  {
    alphabet: 'ง',
    thaiExamplePrefix: 'งอ',
    thaiExampleDescription: 'งู',
    romanTransliterationPrefix: 'ngaw',
    romanTransliteration: 'ngu',
    romanDescription: 'Snake',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/ngaw-ngu.webp',
    order: 32
  },
  {
    alphabet: 'น',
    thaiExamplePrefix: 'นอ',
    thaiExampleDescription: 'หนู',
    romanTransliterationPrefix: 'naw',
    romanTransliteration: 'nuu',
    romanDescription: 'Mouse',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/naw-nuu.webp',
    order: 33
  },
  {
    alphabet: 'ณ',
    thaiExamplePrefix: 'ณอ',
    thaiExampleDescription: 'เณร',
    romanTransliterationPrefix: 'naw',
    romanTransliteration: 'naan',
    romanDescription: 'Novice monk',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/naw-naan.webp',
    order: 34
  },
  {
    alphabet: 'ม',
    thaiExamplePrefix: 'มอ',
    thaiExampleDescription: 'ม้า',
    romanTransliterationPrefix: 'maw',
    romanTransliteration: 'maa',
    romanDescription: 'Horse',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/maw-maa.webp',
    order: 35
  },
  {
    alphabet: 'ย',
    thaiExamplePrefix: 'ยอ',
    thaiExampleDescription: 'ยักษ์',
    romanTransliterationPrefix: 'yaw',
    romanTransliteration: 'yuk',
    romanDescription: 'Giant',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/yaw-yuk.webp',
    order: 36
  },
  {
    alphabet: 'ญ',
    thaiExamplePrefix: 'ญอ',
    thaiExampleDescription: 'หญิง',
    romanTransliterationPrefix: 'yaw',
    romanTransliteration: 'ying',
    romanDescription: 'Woman',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/yaw-ying.webp',
    order: 37
  },
  {
    alphabet: 'ร',
    thaiExamplePrefix: 'รอ',
    thaiExampleDescription: 'เรือ',
    romanTransliterationPrefix: 'raw',
    romanTransliteration: 'rua',
    romanDescription: 'Boat',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/raw-rua.webp',
    order: 38
  },
  {
    alphabet: 'ล',
    thaiExamplePrefix: 'ลอ',
    thaiExampleDescription: 'ลิง',
    romanTransliterationPrefix: 'law',
    romanTransliteration: 'ling',
    romanDescription: 'Monkey',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/law-ling.webp',
    order: 39
  },
  {
    alphabet: 'ฬ',
    thaiExamplePrefix: 'ฬอ',
    thaiExampleDescription: 'จุฬา',
    romanTransliterationPrefix: 'law',
    romanTransliteration: 'julaa',
    romanDescription: 'Kite',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/law-julaa.webp',
    order: 40
  },
  {
    alphabet: 'ว',
    thaiExamplePrefix: 'วอ',
    thaiExampleDescription: 'แหวน',
    romanTransliterationPrefix: 'waw',
    romanTransliteration: 'waen',
    romanDescription: 'Ring',
    isConsonant: true,
    consonantGroup: 'low',
    imageSrc: '/waw-waen.webp',
    order: 41
  }
]


export default thaiAlphabet